[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "care-cartography-api"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
  "fastapi[standard]",
  "pydantic",
  "uvicorn[standard]",
  "sqlalchemy",
  "psycopg2-binary",
  "alembic",
  "python-dotenv",
]

[project.optional-dependencies]
dev = [
  "ruff",
  "black",
]